FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Buscape API TESTS

## Buscape GET de pedidos NEW [/buscape/orders/v2/status/new]

### Buscape GET orders NEW [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"NEW",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
                 }
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos ACCEPT [/buscape/orders/v2/status/accept]

### Buscape GET orders ACCEPT [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"ACCEPT",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos NOT ACCEPT [/buscape/orders/v2/status/not_accept]

### Buscape GET orders NOT ACCEPT [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"NOT_ACCEPT",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos PENDING [/buscape/orders/v2/status/pending]

### Buscape GET orders PENDING [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"PENDING",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos APPROVED [/buscape/orders/v2/status/approved]

### Buscape GET orders APPROVED [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"APPROVED",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos NOT APPROVED [/buscape/orders/v2/status/not_approved]

### Buscape GET orders NOT APPROVED [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"NOT_APPROVED",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos CANCELLED [/buscape/orders/v2/status/cancelled]

### Buscape GET orders CANCELLED [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"CANCELLED",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos INVOICED [/buscape/orders/v2/status/invoiced]

### Buscape GET orders INVOICED [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"INVOICED",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos IN HOSTING [/buscape/orders/v2/status/in_hosting]

### Buscape GET orders IN HOSTING [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"IN_HOSTING",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }


## Buscape GET de pedidos IN ROUTE [/buscape/orders/v2/status/in_route]

### Buscape GET orders IN ROUTE [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"IN_ROUTE",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos RETRYING [/buscape/orders/v2/status/retrying]

### Buscape GET orders RETRYING [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"RETRYING",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos REVERSAL [/buscape/orders/v2/status/reversal]

### Buscape GET orders REVERSAL [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"REVERSAL",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }


## Buscape GET de pedidos DELIVERED [/buscape/orders/v2/status/delivered]

### Buscape GET orders DELIVERED [GET]

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"DELIVERED",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"001",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape GET de pedidos POR ID [/buscape/orders/{id}]

### Buscape GET orders POR ID [GET]

+ Parameters

    + id

+ Response 200 (application/json)

        {
            "orderID":"1",
            "orderStatus":"NEW",
            "orderedItems":[
                {
                "sku":"1",
                "skuSellerId":"94",
                "quantity":"1",
                "price":"99",
                "discount":"0"
                }
            ],
            "paymentMethods":[
                {
                "method":"CARTAO",
                "amount":"109",
                "installments":"1",
                "paymentDueAt":"2017-05-24T16:50:54.497Z",
                "approvedAt":"2017-05-24T16:50:54.497Z"
                }
            ],
            "sellerOrder":"00001",
            "totalFreight":"10",
            "purchaseAt":"1998-12-06T17:05:54.412Z",
            "lastUpdateAt":"2022-07-12T03:21:43.164Z",
            "clientProfileData":{
                "email":"teste@teste.com",
                "firstName":"Teste",
                "lastName":"Testando",
                "documentType":"CPF",
                "document":"147258369",
                "phone":"1177777899",
                "corporate":{
                "name":"Corporate Teste",
                "tradeName":"Corporate",
                "stateInscription":"1",
                "phone":"11"
            }
            },
           "shippingInfo":[
              {
                 "address":{
                    "addressType":"RESIDENCIAL",
                    "receiverName":"vinni teste",
                    "postalCode":"17560000",
                    "city":"vera cruz",
                    "state":"SP",
                    "country":"BRASIL",
                    "street":"teste",
                    "number":"123",
                    "neighborhood":"ACAPULCO",
                    "complement":"testando",
                    "reference":"perto do teste"
             },
         "deliveries":[
            {
               "item":{
                  "sku":"1",
                  "skuSellerId":"001"
               },
               "selectedSla":"",
               "lockTTL":"0",
               "otd":{
                  "shippingEstimate":"5",
                  "transitTime":"1",
                  "crossDockingTime":"1",
                  "scheduledAt":"2017-05-24T16:50:54.540Z",
                  "scheduledPeriod":"MANHA"
               },
               "trackingNumber":"",
               "sellerDeliveryId":"",
               "freightPrice":"10",
               "freightCost":"8",
               "additionalInfo":"",
               "carrier":{
                  "name":"",
                  "cnpj":""
               },
               "tracking":{
                  "description":"accept",
                  "occurredAt":"2017-05-24T16:50:54.540Z",
                  "controlPoint":"accept"
               },
               "invoice" : {
                  "number": "1",
                  "value": "10",
                  "url": "",
                  "issuanceDate": "2017-05-24T16:50:54.540Z",
                  "invoiceKey": ""
               },
               "giftWrap":{
                  "available":"false",
                  "value":"0",
                  "giftCard":{
                     "from":"",
                     "to":"",
                     "message":""
                  }
               }
            }
         ]
        }
        ]
        }



## Buscape POST de estoque [/buscape/stock]

### Buscape POST Estoque [POST]

+ Request (application/json)

    + Headers
    
            app-token: S0JQ9E6q4hve
    
    + Body
    
            {
                "buscapeID" : "string",
                "orderedItems": [
                  {
                    "skuSellerId" : "001",
                    "quantity" : "2",
                    "postalCode" : "string"
                  }
                ]
            }

+ Response 201 (application/json)

        [  
           {  
              "buscapeID":"number",
              "skuSellerId":"number",
              "available":"number",
              "crossDockingTime":"number",
              "message":"string"
           }
        ]




## Buscape POST de pedido [/buscape/notifications/{token}/notify_order_buscape]

### Buscape POST Pedido [POST]

+ Parameters

    + token

+ Request (application/json)

    + Headers
    
            app-token: S0JQ9E6q4hve
    
    + Body
    
            {
               "eventDate":"2017-06-1",
               "sellerId":"01",
               "orderUri":"teste",
               "order": {"orderID": "1", "orderStatus": "NEW"}
            }

+ Response 201 (application/json)


    + Body

            {
              "message_response": true,
              "data_response": {
                "success": true
              }
            }


## Buscape POST ACEITE [/buscape/acceptence]

### Buscape POST Aceite [POST]

+ Request

           {
                "eventDate":"date",
                "accepted" : "boolean",
                "sellerOrder" : "string",
                "message" : "string"
            }

+ Response 201 (application/json)



## Atualiza Tracking de Pedido [/buscape/orders/v2/1/tracking]

### Atualiza Traacking de Pedido [POST]

+ Request (application/json)

        [
           {
              "item":{
                 "sku":"string",
                 "skuSellerId":"string"
              },
              "selectedSla":"string",
              "lockTTL":"number",
              "otd":{
                 "shippingEstimate":"number",
                 "transitTime":"number",
                 "crossDockingTime":"number",
                 "scheduledAt":"date",
                 "scheduledPeriod":"string"
              },
              "trackingNumber":"string",
              "sellerDeliveryId":"string",
              "freightPrice":"number",
              "freightCost":"number",
              "additionalInfo":"string",
              "carrier":{
                 "name":"string",
                 "cnpj":"string"
              },
              "invoice":{
                 "number":"number",
                 "value":"number",
                 "url":"string",
                 "issuanceDate":"date",
                 "invoiceKey":"string"
              },
              "tracking":{
                 "description":"string",
                 "occurredAt":"date",
                 "controlPoint":"string"
              }
           }
        ]

+ Response 201 (application/json)